apiVersion: v1
kind: Secret
metadata:
  name: mysql-secret
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: {{ required "db.rootPassword is required" .Values.db.rootPassword | quote }}
  MYSQL_DATABASE: {{ .Values.db.name | quote }}
